services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: awesome_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  firebase_emulator:
    image: voraciousdev/firebase-tools:latest
    container_name: firebase
    environment:
      # replace with your Firebase project ID (used by the emulator)
      FIREBASE_PROJECT_ID: demo-project
    ports:
      - "4000:4000"   # Emulator Suite UI
      - "8080:8080"   # Firestore emulator
      - "9099:9099"   # Auth emulator
    volumes:
      # mount your project (so it sees firebase.json, firestore.rules, etc.)
      - .:/firebase/volume

volumes:
  pgdata:

networks:
  default:
    name: awesome-network
